version: '3'

networks:

  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:

  redis-cluster:
    image: redis:latest
    command: redis-cli -p 7001 --cluster create 10.0.0.11:7001 10.0.0.12:7002 10.0.0.13:7003  --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
    networks:
      redisnet:
        ipv4_address: 10.0.0.2

  redis-1:
    build: ./redis
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7001
    networks:
      redisnet:
        ipv4_address: 10.0.0.11

  redis-2:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7002
    networks:
      redisnet:
        ipv4_address: 10.0.0.12

  redis-3:
    image: redis-cluster-node
    environment:
      X_REDIS_PORT: 7003
    networks:
      redisnet:
        ipv4_address: 10.0.0.13


